/**
 * Merges one anchor's two legs into a single canonical `Report`.
 *
 * The merged artifact is a plain `Report` - schemaVersion, domain, network, timestamp,
 * results - and nothing else, so anything written against `src/core/report.ts` can read
 * it and no REPORT_SCHEMA_VERSION bump is needed for the crawler to exist. Provenance
 * for a leg that did not run travels as ordinary `CheckResult` markers inside `results`,
 * which is also what keeps summary.json regenerable from the archive alone (§4.2).
 */
import { CRAWL_UNAVAILABLE_SUFFIX, isCrawlUnavailable } from "./inconclusive-ids.mjs";

/** The SEP an id belongs to: the segment before its first dot. */
function sepOf(id) {
  if (typeof id !== "string") {
    return undefined;
  }
  const dot = id.indexOf(".");
  return dot === -1 ? undefined : id.slice(0, dot);
}

/**
 * Prefixes a leg owns, each with a trailing dot.
 *
 * The dot matters: without it "sep1" would claim "sep10.negative.expired", since that id
 * starts with the characters "sep1". With it, "sep1." does not match "sep10.".
 */
export function ownedPrefixes(leg) {
  return leg.owns.map((sep) => `${sep}.`);
}

/** Whether `id` belongs to `leg`. */
export function ownsResult(leg, id) {
  return typeof id === "string" && ownedPrefixes(leg).some((prefix) => id.startsWith(prefix));
}

/**
 * One marker per SEP in a leg that could not run, so a per-SEP view shows each as "not
 * run" rather than showing nothing.
 *
 * `warn`, never `fail`: a fail asserts the anchor is non-conformant, which this run did
 * not observe. Not omitted either - a silently missing SEP would let the dashboard show
 * "10/10 passed" while concealing that a third of the checks never ran, which is exactly
 * the silently-wrong dashboard data §4.1 warns about.
 */
export function unavailableMarkers(leg, reason) {
  return leg.owns.map((sep) => ({
    id: `${sep}${CRAWL_UNAVAILABLE_SUFFIX}`,
    description: `${sep.toUpperCase()} checks did not run in this crawl`,
    status: "warn",
    severity: "warning",
    message: `Not run: the ${leg.id} leg did not produce a usable report (${reason}). This is a crawler limitation, not a finding about this anchor.`,
  }));
}

/**
 * Whether a leg's report is safe to merge.
 *
 * §4.1: a stored report whose schemaVersion exceeds the reader's must be skipped or
 * migrated explicitly, never parsed optimistically. The same rule is applied to a report
 * the crawler just produced, where a mismatch means the crawler is running a CLI build it
 * does not understand - which should be surfaced, not merged.
 */
export function validateLegSchema(report, supportedVersion) {
  if (!report || typeof report !== "object") {
    return { ok: false, reason: "no report" };
  }
  if (report.schemaVersion === undefined) {
    return {
      ok: false,
      reason: "report has no schemaVersion; it predates the field, so the CLI that produced it is older than this crawler",
    };
  }
  if (typeof report.schemaVersion !== "number" || !Number.isInteger(report.schemaVersion)) {
    return { ok: false, reason: `schemaVersion is not an integer: ${JSON.stringify(report.schemaVersion)}` };
  }
  if (report.schemaVersion > supportedVersion) {
    return {
      ok: false,
      reason: `unsupported schemaVersion ${report.schemaVersion} (this crawler understands ${supportedVersion})`,
    };
  }
  return { ok: true };
}

/**
 * Merges legs into one Report.
 *
 * `legs` entries are `{ leg, report, reason }`: a usable report, or a reason it is
 * unavailable. Legs are processed in the order given, which fixes the order of the
 * merged results and so keeps day-to-day diffs of the archive stable.
 *
 * `timestamp` is generated by the caller when the anchor's crawl begins, and is not taken
 * from either leg. The legs are minutes apart; picking one leg's clock would imply a
 * precision the merged record does not have, and would make the entry's time drift with
 * whichever leg happened to be slower.
 */
export function mergeLegs({ domain, network, timestamp, legs, supportedVersion }) {
  // Validated up front, because whether a leg's *owner* produced anything decides how the
  // other leg's non-owned results are treated below - a decision that cannot be made from
  // inside a single forward pass.
  const validated = legs.map(({ leg, report, reason }) => {
    const validation = report ? validateLegSchema(report, supportedVersion) : { ok: false, reason: reason ?? "no report" };
    return { leg, report, ok: validation.ok, reason: validation.ok ? undefined : (reason ?? validation.reason) };
  });

  const results = [];
  const unavailable = [];
  const claimed = new Set();

  for (const { leg, report, ok, reason } of validated) {
    if (!ok) {
      unavailable.push({ leg: leg.id, reason });
      results.push(...unavailableMarkers(leg, reason));
      continue;
    }

    if (report.domain !== domain || report.network !== network) {
      // A crawler bug, not an anchor problem: the wrong file was read for this entry.
      throw new Error(
        `leg ${leg.id} reports ${report.domain}/${report.network}, expected ${domain}/${network}`,
      );
    }

    for (const result of report.results ?? []) {
      // Ownership filter. The kyc leg runs sep1 and sep10 as dependencies of sep12 (see
      // build-cli-args.mjs), so both legs emit sep1.*/sep10.* on every ordinary run.
      // Filtering by declared ownership makes the union collision-free by construction
      // rather than by luck, and keeps the core leg's copy - the one measured without
      // --no-write, with the client-domain and negative-case paths enabled.
      if (ownsResult(leg, result.id)) {
        results.push(result);
        claimed.add(result.id);
      } else if (!claimed.has(result.id) && !isOwnedByUsableLeg(validated, result.id)) {
        // Kept, from the first leg that produced it, when no leg that actually ran owns
        // it: either an id no leg declares (a future SEP, or a renamed prefix), or one
        // whose owning leg failed. The second case is why this is worth doing - if the
        // core leg dies, the kyc leg's dependency run still measured SEP-1 and SEP-10, and
        // discarding that in favour of a bare "did not run" marker would throw away a real
        // measurement. The marker for the failed leg still stands alongside it, so the run
        // is still visibly partial.
        results.push(result);
        claimed.add(result.id);
      }
    }
  }

  // A SEP that was rescued above must not also carry a "did not run" marker: its checks
  // did run, and publishing both a real verdict and a contradicting marker for the same
  // SEP is exactly the silently-wrong dashboard data §4.1 warns about. Markers for the
  // SEPs that genuinely were not measured stay, so the run is still visibly partial.
  const measured = new Set(results.filter((r) => !isCrawlUnavailable(r)).map((r) => sepOf(r.id)));

  return {
    report: {
      schemaVersion: supportedVersion,
      domain,
      network,
      timestamp,
      results: results.filter((r) => !(isCrawlUnavailable(r) && measured.has(sepOf(r.id)))),
    },
    unavailable,
  };
}

function isOwnedByUsableLeg(validated, id) {
  return validated.some(({ leg, ok }) => ok && ownsResult(leg, id));
}
